baseURL = "https://practical-beaver-f592e0.netlify.com/"
languageCode = "en-us"
title = "kickFLIP"

[permalinks]
  posts = "/:filename/"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 3
  [[menu.main]]
    name = "Skating"
    url = "/tags/skating/"
    weight = 4
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

[params]
  dateFormat = "January 2, 2006"
  homeText = "kickFLIP is a theme for the static site generator Hugo."

[taxonomies]
  tag = "tags"